#!/bin/bash

chmod +x /Applications/SubutaiControlCenter.app/Contents/MacOS/SubutaiControlCenter
chmod +x /Applications/SubutaiControlCenter.app/Contents/MacOS/SubutaiControlCenter_osx
mkdir -p /Applications/Subutai
chown -R $USER /Applications/Subutai*

mkdir -p /usr/local/share/subutai/bin
mkdir -p /usr/local/share/subutai/etc
mkdir -p /usr/local/share/subutai/resources
chown -R $USER /usr/local/bin
chown -R $USER /usr/local/share/subutai
ln -s /Applications/SubutaiControlCenter.app/Contents/MacOS/SubutaiControlCenter /usr/local/bin/SubutaiControlCenter
