#pragma once

typedef enum run_libssh2_error {
  RLE_SUCCESS = 1000,
  RLE_WRONG_ARGUMENTS_COUNT,
  RLE_WSA_STARTUP,
  RLE_LIBSSH2_INIT,
  RLE_INET_ADDR,
  RLE_CONNECTION_TIMEOUT,
  RLE_CONNECTION_ERROR,
  RLE_LIBSSH2_SESSION_INIT,
  RLE_SESSION_HANDSHAKE,
  RLE_SSH_AUTHENTICATION,
  RLE_LIBSSH2_CHANNEL_OPEN,
  RLE_LIBSSH2_CHANNEL_EXEC,
  RLE_LIBSSH2_EXIT_CODE_NOT_NULL
} run_libssh2_error_t;

const char* run_libssh2_error_to_str(run_libssh2_error_t err);
