#pragma once

typedef enum run_update_erros {
  RUE_SUCCESS = 0,
  RUE_WRONG_ARGUMENTS_COUNT,
  RUE_WSA_STARTUP,
  RUE_LIBSSH2_INIT,
  RUE_INET_ADDR,
  RUE_CONNECTION_TIMEOUT,
  RUE_CONNECTION_ERROR,
  RUE_LIBSSH2_SESSION_INIT,
  RUE_SESSION_HANDSHAKE,
  RUE_SSH_AUTHENTICATION,
  RUE_LIBSSH2_CHANNEL_OPEN,
  RUE_LIBSSH2_CHANNEL_EXEC,
  RUE_LIBSSH2_EXIT_CODE_NOT_NULL
} run_update_erros_t;
