#!/bin/sh
set -e
if which update-icon-caches >/dev/null 2>&1 ; then
    update-icon-caches /usr/share/icons/Tray_icon_set-07.png
fi

if [ -d /opt/subutai/lib ]; then
  rm -rf /opt/subutai/lib
fi

if [ -d /opt/subutai/Libs ]; then
  rm -rf /opt/subutai/Libs
fi

if [ -d /opt/subutai/log ]; then
  rm -rf /opt/subutai/log
fi

if [ -L /usr/bin/SubutaiTray ]; then
  rm /usr/bin/SubutaiTray
fi

count=`ls -1 /opt/subutai/bin/*.qm 2>/dev/null | wc -l`
if [ $count != 0 ]; then 
  rm /opt/subutai/bin/*.qm
fi 

if [ -f /opt/subutai/lbin/SubutaiTray ]; then
  rm /opt/subutai/bin/SubutaiTray
fi

if [ -f /opt/subutai/lbin/subutai-tray ]; then
  rm /opt/subutai/bin/subutai-tray
fi

if [ -f /usr/share/applications/SubutaiTray.desktop ]; then
  rm /usr/share/applications/SubutaiTray.desktop
fi



