#!/bin/bash

mkdir -p /opt/subutai/log
mkdir -p /opt/subutai/bin
mkdir -p /opt/subutai/lib
mkdir -p /opt/subutai/Libs

chmod -R 0777 /opt/subutai/log
chmod -R 0777 /opt/subutai/bin

tray_script=/opt/subutai/bin/SubutaiControlCenter
tray_link=/usr/bin/SubutaiControlCenter
tray_binary=/opt/subutai/bin/subutai-control-center

if [ -L $tray_link ]; then
  rm -rf $tray_link
fi

tar zxf /tmp/subutai/SubutaiControlCenter.tar.gz -C /tmp/subutai/

cp /tmp/subutai/SubutaiControlCenter/Libs/* /opt/subutai/Libs/
cp /tmp/subutai/SubutaiControlCenter/bin/*.qm /opt/subutai/bin
cp /tmp/subutai/SubutaiControlCenter/bin/subutai-control-center $tray_binary

echo "#!/bin/bash" > $tray_script
echo "LD_LIBRARY_PATH=/opt/subutai/Libs/ $tray_binary" >> $tray_script
ln -s $tray_script $tray_link
chmod +x $tray_link
chmod +x $tray_script
chmod +x $tray_binary


desktop_file=/tmp/SubutaiControlCenter.desktop

echo "[Desktop Entry]" > $desktop_file
echo "Version=1.0" >> $desktop_file
echo "Name=Subutai Control Center" >> $desktop_file
echo "Comment=Subutai Control Center Application" >> $desktop_file
echo "Keywords=Internet" >> $desktop_file
echo "Exec=/usr/bin/SubutaiControlCenter" >> $desktop_file
echo "Terminal=false" >> $desktop_file
echo "Type=Application" >> $desktop_file
echo "Icon=/usr/share/icons/cc_icon.png" >> $desktop_file
echo "Categories=GNOME;Network" >> $desktop_file
echo "StartupNotify=true" >> $desktop_file

desktop-file-install $desktop_file
ldconfig

which_res=$(which p2p)
which_res_code=$?
settings_file=~/.config/subutai/subutai_tray.ini
mkdir -p ~/.config/subutai/
default_snap_files=(/snap/subutai-dev/current/bin/p2p /snap/subutai/current/bin/p2p /snap/subutai-master/current/bin/p2p /opt/subutai/bin/p2p)
p2p_path="/opt/subutai/bin/p2p"

if [ $which_res_code -eq 0 ]; then
	p2p_path=$which_res
else
	for df in ${default_snap_files[@]}; do
		if [ -e $df ]; then
		  $df debug
		  rc=$?
		  if [ $rc -eq 0 ]; then
			  p2p_path=$df
			  break
		  fi
		fi
	done
fi

if [ ! -e $settings_file ]; then
	echo "[General]" > $settings_file
fi

echo "P2P_Path=$p2p_path" >> $settings_file

bin_path=`which SubutaiControlCenter`
if [ -z "$bin_path" ]; then
  echo "Couldn't launch SubutaiControlCenter"
else
  $bin_path
fi
