#!/bin/bash

mkdir -p /opt/subutai/log
chmod -R 0777 /opt/subutai/log
chmod -R 0777 /opt/subutai/bin

if [ -L /usr/bin/SubutaiTray ]; then
  rm -rf /usr/bin/SubutaiTray
fi
chmod +x /opt/subutai/bin/SubutaiTray
ln -s /opt/subutai/bin/SubutaiTray /usr/bin/SubutaiTray

desktop_file=/tmp/SubutaiTray.desktop

echo "[Desktop Entry]" > $desktop_file
echo "Version=1.0" >> $desktop_file
echo "Name=Subutai Tray" >> $desktop_file
echo "Comment=Subutai Tray Application" >> $desktop_file
echo "Keywords=Internet" >> $desktop_file
echo "Exec=/opt/subutai/bin/SubutaiTray" >> $desktop_file
echo "Terminal=false" >> $desktop_file
echo "Type=Application" >> $desktop_file
echo "Icon=/usr/share/icons/Tray_icon_set-07.png" >> $desktop_file
echo "Categories=GNOME;Network" >> $desktop_file
echo "StartupNotify=true" >> $desktop_file

desktop-file-install $desktop_file
ldconfig

which_res=$(which p2p)
which_res_code=$?
settings_file=/opt/subutai/bin/subutai_tray.ini
default_snap_files=(/snap/subutai-dev/current/bin/p2p /snap/subutai/current/bin/p2p /snap/subutai-master/current/bin/p2p /opt/subutai/bin/p2p)
p2p_path="/opt/subutai/bin/p2p"

if [ $which_res_code -eq 0 ]; then
	p2p_path=$which_res
else
	for df in ${default_snap_files[@]}; do
		if [ -e $df ]; then
		  $df debug
		  rc=$?
		  if [ $rc -eq 0 ]; then
			  p2p_path=$df
			  break
		  fi
		fi
	done
fi

if [ ! -e $settings_file ]; then
	echo "[General]" > $settings_file
fi

echo "P2P_Path=$p2p_path" >> $settings_file
