#!/bin/sh
set -e
kill -9 $(ps -A | grep "Subutai" | awk {'print $1'})
if which update-icon-caches >/dev/null 2>&1 ; then
    update-icon-caches /usr/share/icons/cc_icon_resized.png
fi

if [ -d /opt/subutai/lib ]; then
  rm -rf /opt/subutai/lib
fi

if [ -d /opt/subutai/Libs ]; then
  rm -rf /opt/subutai/Libs
fi

if [ -d /opt/subutai/log ]; then
  rm -rf /opt/subutai/log
fi

if [ -L /usr/bin/SubutaiControlCenter ]; then
  rm /usr/bin/SubutaiControlCenter
fi

count=`ls -1 /opt/subutai/bin/*.qm 2>/dev/null | wc -l`
if [ $count != 0 ]; then 
  rm /opt/subutai/bin/*.qm
fi 

if [ -f /opt/subutai/lbin/SubutaiControlCenter ]; then
  rm /opt/subutai/bin/SubutaiControlCenter
fi

if [ -f /opt/subutai/lbin/subutai-control-center ]; then
  rm /opt/subutai/bin/subutai-control-center
fi

if [ -f /usr/share/applications/SubutaiControlCenter.desktop ]; then
  rm /usr/share/applications/SubutaiControlCenter.desktop
fi



