#!/bin/sh

if [ -d /opt/subutai/tray ]; then
rm -rf /opt/subutai/tray
fi

if [ -L /usr/bin/subutai-tray ]; then
rm -rf /usr/bin/subutai-tray
fi

if [ -L /usr/bin/libssh2_app ]; then
rm -rf /usr/bin/libssh2_app
fi
